const REPLACEMENTS: Array<[string, string]> = [
  ['concluï¿½do', 'concluído'],
  ['Concluï¿½do', 'Concluído'],
  ['concluiÌdo', 'concluído'],
  ['NÃƒÂ£o', 'Não'],
  ['nÃƒÂ£o', 'não'],
  ['possÃƒÂ­vel', 'possível'],
  ['VocÃƒÂª', 'Você'],
  ['vocÃƒÂª', 'você'],
  ['VocÃª', 'Você'],
  ['vocÃª', 'você'],
  ['cartÃƒÂ£o', 'cartão'],
  ['cartÃ£o', 'cartão'],
  ['organizaÃƒÂ§ÃƒÂ£o', 'organização'],
  ['organizaÃ§Ã£o', 'organização'],
  ['descriÃƒÂ§ÃƒÂ£o', 'descrição'],
  ['descriÃ§Ã£o', 'descrição'],
  ['ediÃƒÂ§ÃƒÂ£o', 'edição'],
  ['ediÃ§Ã£o', 'edição'],
  ['comentÃƒÂ¡rio', 'comentário'],
  ['comentÃ¡rio', 'comentário'],
  ['UsuÃƒÂ¡rio', 'Usuário'],
  ['UsuÃ¡rio', 'Usuário'],
  ['ÃƒÂ¡', 'á'],
  ['ÃƒÂ¢', 'â'],
  ['ÃƒÂ£', 'ã'],
  ['ÃƒÂ©', 'é'],
  ['ÃƒÂª', 'ê'],
  ['ÃƒÂ­', 'í'],
  ['ÃƒÂ³', 'ó'],
  ['ÃƒÂ´', 'ô'],
  ['ÃƒÂµ', 'õ'],
  ['ÃƒÂº', 'ú'],
  ['ÃƒÂ§', 'ç'],
  ['Ãƒ\u0081', 'Á'],
  ['Ãƒ\u0089', 'É'],
  ['Ãƒ\u0093', 'Ó'],
  ['Ãƒ\u0087', 'Ç'],
  ['Ã¡', 'á'],
  ['Ã¢', 'â'],
  ['Ã£', 'ã'],
  ['Ã©', 'é'],
  ['Ãª', 'ê'],
  ['Ã­', 'í'],
  ['Ã³', 'ó'],
  ['Ã´', 'ô'],
  ['Ãµ', 'õ'],
  ['Ãº', 'ú'],
  ['Ã§', 'ç'],
  ['â€™', '’'],
  ['â€œ', '“'],
  ['â€\u009d', '”'],
  ['â€“', '–'],
  ['â€”', '—']
]

export function normalizeMojibake(value: string): string {
  let nextValue = value
  for (const [broken, fixed] of REPLACEMENTS) {
    nextValue = nextValue.replaceAll(broken, fixed)
  }
  return nextValue.normalize('NFC')
}
